### PR TITLE
Minor updates to ExprTk

### PR DESCRIPTION
**Pull request by ArashPartow**
- Updated multi-sub expression operator to return final sub-expression type.
- Updates to exprtk_disable_return_statement macro for disabling return statements and associated exceptions at the source code level.
- Various other updates

### CODE REVIEW

**Comment by chrgod** [comment]
Hi Arash,

could you open the PR on https://i10git.cs.fau.de/walberla/walberla/? Then our automatic builds would check if there are any warnings due to the changes. You should be able to login into our GitLab server with your GitHub account (hit the GitHub icon on the login page. Thanks a lot for changes! Updating exprtk was still on my todo list though 😄.

**Comment by chrgod** [comment]
Also, you should be able to fork on our GitLab server now ;-)

**Comment by ArashPartow** [comment]
ok will do.

**Comment by ArashPartow** [comment]
I tried to create a fork but got the following error: 

> Fork Error!
> You tried to fork walberla / waLBerla but it failed for the following reason:
> – Limit reached Personal project creation is not allowed. Please contact your administrator with questions

**Comment by chrgod** [comment]
Sorry about that. That is some kind of unintended behavior on our side: it seems that whenever you login with the GitHub Account your account gets reset to a "read only" account. You should have received a "set password" link. When you have set a password you can login via the "standard" tab on https://i10git.cs.fau.de/users/sign_in .

**Pull request closed without merging**
